### ISSUE TITLE
DIY guide followed; Fails 

### ISSUE THREAD

**Issue by e-karma** [stickyroll/react-stickyroll#125]
**Describe the bug**

on the 3rd phase of the DIY section, after adding the <Skip /> component and pressing it, the app breaks with this error. 
"TypeError: Cannot read property 'scrollIntoView' of null"

based on this line of codes internals and the 'scrollIntoView' method. 

"scrollTo(`${props.prefix}/skip`, e.target, {"

![Screen Shot 2019-03-08 at 8 21 29 PM](https://user-images.githubusercontent.com/6776633/54064166-02fb1580-41e0-11e9-9498-28130a02f414.png)
**To Reproduce**
implement this phase of docs 
https://stickyroll.github.io/react-stickyroll/doc/guide/creating-plugins/Readme.html?guides-enabled=true

**Comment by pixelass** [comment]
Thank you for reporting this issue. I'll look into it.

A working example can be found here: https://github.com/stickyroll/react-stickyroll/tree/master/guide/creating-plugins/src
