### ISSUE TITLE
DIY guide code incorrect.

### ISSUE THREAD

**Issue by n8-dev** [stickyroll/react-stickyroll#227]
**Describe the bug**
Example code in [adding deep links](https://stickyroll.github.io/react-stickyroll/doc/guide/configue-stickyroll/Readme.html?guides-enabled=true#3.-adding-deep-links) section.

**To Reproduce**
1. Go to [docs](https://stickyroll.github.io/react-stickyroll/doc/guide/configue-stickyroll/Readme.html?guides-enabled=true#3.-adding-deep-links)
2. Copy example to your file
3. Compile error

**Codesandbox**
n/a

**Expected behavior**
Example code runs.

**Screenshots**
N/a

**Additional context**
Have submitted a PR #228

**Comment by pixelass** [comment]
Thank you for your contribution.
I'm currently refactoring the repo so looking into this PR will take a while. So far everything looks good. It's just blocked by my local refactoring.
