### ISSUE TITLE
Anchors with Stickyroll Hook?

### ISSUE THREAD

**Issue by nullboundary** [stickyroll/react-stickyroll#349]
Hello,

I am using the stickyroll hooks API to build a custom scroll progress bar/pager. Is it possible to use anchors similar to how it is done in the regular stickyroll API `<Stickyroll pages={headlines} anchors=""/>`?

If stickyroll hooks doesn't have anchors implemented yet, can you explain how I could add them into my stickyroll page component and how can I make the stickyroll jump to a particular part on the page? 

Thanks!

**Comment by pixelass** [comment]
Thank you for reporting this issue. 

Adding anchors with hooks is currently a manual process. I will consider this as a feature or add it to the documentation. 

You can see a very simple implementation here: https://codesandbox.io/s/stickyroll-hooks-anchors-1u4wq

**Comment by nullboundary** [comment]
Hi, 

Thanks for the example, its exactly what I need to add anchors with hooks! You should add it to the documentation. I am sure others might need it as well.

**Comment by pixelass** [comment]
thx for the tip. I am working on a new documentation since the library I used is unmaintained. It will take a while though.
