### ISSUE TITLE
how to responsive for mobile

### ISSUE THREAD

**Issue by abbasashraf** [stickyroll/react-stickyroll#370]

**Comment by pixelass** [comment]
Thank you for reaching out. Sadly I don't fully understand the question.

Stickyroll is a full-view container so you can just use the same technique as you would usually use for content.

If this answers your question please close the issue. 

Thank you

**Comment by abbasashraf** [comment]
```
const renderPagers = (props) => (
  <Inner withPagers="right">
    <Pagers
      {...props}
      prefix={props.anchors}
      showLabels={true}
      position="right"
    />
    <Content style={style}>
      <div style={style}>pageIndex :{props.pageIndex}</div>
    </Content>
  </Inner>
);

const Test = ({}) => {
  return (
    <Stickyroll
      pages={5}
      render={renderPagers}
      anchors={"!/examples/slideshow"}
    />
  );
};
```

on the portrait view, it's not working, when scrolling and click on pager button it's not changing the index and all others props, it remains to view the first screen/index

**Comment by pixelass** [comment]
Maybe you can create a [codesandbox](https://codesandbox.io/) for it so I can reproduce the issue. We provide a template that can be adjusted to your needs: https://codesandbox.io/s/m1wxp21rx

Also please provide some information about your setup, browser ...etc. as requested by our issue template for bugs: https://github.com/stickyroll/react-stickyroll/issues/new?template=bug_report.md
