### ISSUE TITLE
Two questions on use

### ISSUE THREAD

**Issue by nadpev** [stickyroll/react-stickyroll#371]
Hi,
Thanks for the great plugin!
Two things I couldn't find, hope its fine I ask here:
this is my code:
`<div className={classes.root}>
            <Header />
            <div>
                <div>

                    <GlobalStyle />
                    <Wrapper ref={wrapper} height={height} >

                        {usedPages}

                        <Pagers
                            className="pagesSimu"
                            triggers={triggers}
                            pageCount={pageCount}
                            progress={progress}
                            pageIndex={pageIndex}
                        />
                        

                    </Wrapper>
                    <Pages className="pages" targets={targets} />
<Footer />
                </div>
            </div>
        </div >`
It is now working fine in terms of fullscreen scrolling and having a pager following the progress.
My two problems are:
1. Disabling the sticky scrolling when I reach the end of a specific container - as you can see I have a footer underneath my wrapper. I currently can't scroll under the elements that are in {usedPages}, which means I can't scroll to see the footer - the page just jumps back up.

2. Enabling factor and throttle only on a specific page - I have an animation that is triggered by progress on a specific component within the {usedPages} array. For this reason I need to enable the factor and throttle parameters only for this specific component.
How is this possible?
Sorry if my questions are obvious. I'm quite new to this. Tried to follow the guide in your docs but couldn't find answers to my questions there.
Thank you!

**Comment by pixelass** [comment]
It should automatically scroll past stickyroll (this is how `position: sticky` works natively). Please make sure your footer is not using `position: fixed;` or `position: absolute;` or you provide a space for it.

You can see the behavior in this example:  https://stickyroll.github.io/react-stickyroll/ 

As of right now you can't enable throttle or factor on a specific page. You could build something like this yourself though. e.g. use `factor: 1` treat pages 2 + 3 as one. 

**untested**

```js
const startCustomFactor = 1;
const customFactorCount = 2;
const endCustomFactor = startCustomFactor + customFactorCount;
const t = page >= startCustomFactor && page < endCustomFactor ? ((page - startCustomFactor + progress) / customFactorCount) : progress
console.log(t); // should return a custom factor for the pages 1 and 2.
// you can use throttle in a similar way
```
