### ISSUE TITLE
[Bug]: Sticky Roll cannot used if installing on nextjs framework

### ISSUE THREAD

**Issue by azazel404** [stickyroll/react-stickyroll#423]
### Contact Details

gunawan4041@gmail.com

### What happened?

trying install in nextjs framework , after install ,  trying using in page.js
got error like image below, 
any idea for fix this issue ?
![Screenshot_2](https://github.com/pixelass/react-stickyroll/assets/25822411/6c4e8b32-e0ca-435b-876e-fcdaee435513)

### Version

2.x (Default)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pixelass** [comment]
this happens due to the new server components in next.js. 
Since stickyroll uses user-interaction (client component) useEffect is required, therefore the file with your stickyroll should use `'use client'`

See: https://nextjs.org/docs/getting-started/react-essentials#client-components

**Comment by azazel404** [comment]
oh i see, i also didn't realize that it's an issue from the latest nextjs need to add use client

**Comment by pixelass** [comment]
it should only have that issue if you use the new `app` folder (instead of `pages`)
